apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kaltrinai/webstoremanagementbackend:latest
        ports:
        - containerPort: 5000
        env:
          - name: ENVIRONMENT
            value: "Development"
          - name: CONNECTION_STRING
            value: "Host=database;Port=5432;Database=WebStoreManagement;Username=postgres;Password=K@ltr!na8"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:5000"
        resources:
          requests:
            cpu: "5m"
            memory: "512Mi"
          limits:
            cpu: "10m"
            memory: "512Mi"
