apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: dev
  labels:
    app: database
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: kaltrinai/webstoremanagementdatabase:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "10m"
            memory: "512Mi"
          limits:
            cpu: "10m"
            memory: "1Gi"
        env:
        - name: POSTGRES_DB
          value: "WebStoreManagement"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "K@ltr!na8"
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
