apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: production
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
